### ISSUE TITLE
Introdução

### ISSUE THREAD

**Issue by TheMarini** [TheMarini/naasp-api#5]
Usar template "Entrega Final".

**--- Tasks ---**
- [x] Contextualização da área
- [x] Contextualização do problema
- [x] Especificação do cliente
- [x] Objetivo geral
- [x] Objetivos específicos
- [x] Justificativas
